theme: jekyll-theme-minimal
# Site settings
title: Muebles
description: "Write your site description here. It will be used as your sites meta description as well!"
baseurl: "/startbootstrap-clean-blog-jekyll"
url: "https://clasesdeguitarra.github.io/"
